---
- name: Copy file 
  become: true
  copy:
        src: artifact.tar.gz
        dest: /home/ubuntu

- name: Create directory
  file:
    path: /home/ubuntu/backend
    state: directory

- name: Extract file into backend
  ansible.builtin.unarchive:
    src: artifact.tar.gz
    dest: /home/ubuntu/backend

- name: Execute
  become: true
  shell: |   
    cd /home/ubuntu/backend
    npm install
    npm run build   
    pm2 stop default
    pm2 start npm --name "backend" -- start
